version: '3.2'

volumes:
  dbdata:

networks:
  dbclub:

services:
  db:
    image: mysql:5.7
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
    restart: always
    expose: 
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      dbclub:

  api:
    image: bitnami/node
    volumes:
      - ./:/app
    expose:
      - "4000"
    links:
      - db
    depends_on:
      - db
    command: "npm start"
    networks:
      dbclub:

  web:
    image: bitnami/nginx
    volumes:
      - ./deployment/web/api_vhost.conf:/opt/bitnami/nginx/conf/vhosts/api_vhost.conf:ro
    depends_on:
      - api
    links:
      - api:api
    expose:
      - 8081
    ports:
      - 4000:8081
    restart: always
    networks:
      dbclub:
